In [1]:
import numpy as np

In [10]:
# 넘파이 색인 추출 방법
y = np.random.uniform(low=0, high=1, size=(5,3))
print(y)
t = np.array([0, 2, 1, 2, 1])
y[np.arange(y.shape[0]), t]
np.log(0.09)


[[0.35933313 0.98033738 0.75179272]
 [0.61854777 0.69154466 0.94104401]
 [0.7751151  0.54588286 0.95413146]
 [0.54519846 0.98297737 0.59005639]
 [0.25156742 0.49114662 0.27117579]]


-2.4079456086518722

In [3]:
# 랜덤으로(0~99)사이의 50개의 원소를 갖는 배열 생성
np.random.choice(100, 50)

array([40, 66, 84, 59,  3, 31, 35, 44, 51, 61, 89, 60, 50, 75, 97, 70, 14,
       58, 72, 67, 46,  3, 94, 44, 68, 82, 61, 68, 67, 47, 78, 47,  7, 11,
       92, 48, 14, 11, 53, 89, 11, 39, 74, 65, 14, 27, 37, 20,  5, 43])

In [16]:
np.sum(y, axis=0)

array([2.80719214, 2.41315958, 2.95459538])

In [9]:
arr = np.zeros((1,10))
arr[0, 0] = 1
print(arr)

arr = np.empty((0, 10), int)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[]


In [17]:
y = np.random.uniform(low=0, high=1, size=(2,3))
t = np.zeros((2,3))
t[0][0] = 1
t[1][1] = 1

print(y)

delta = 1e-7
# np.log(x) (x>0)
e1 = t*np.log(y+delta)
print(e1)
print(np.sum(e1, axis=1))

[[0.41813702 0.11545386 0.34513503]
 [0.59952392 0.80031804 0.38517773]]
[[-0.87194587 -0.         -0.        ]
 [-0.         -0.22274595 -0.        ]]
[-0.87194587 -0.22274595]


In [4]:
arr = np.random.choice(2, 10)
tf_arr = arr > 0 # 마스킹
print(tf_arr)

[False  True False  True False False  True False  True  True]


In [10]:
a = np.arange(4).reshape((2,2))
b = np.arange(4, 8, 1).reshape((2,2))

print(a)
print(b)

np.dot(a,b)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


array([[ 6,  7],
       [26, 31]])

## Numpy AXIS(축)의 이해

In [30]:
# (2,3,4) 의 1로 구성된 3차원 배열
one = np.ones((2,3,4))
print(one)
print(one.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)


In [28]:
# 3차원 배열의 첫번째 축(Axis=0)를 기준으로 sum을 수행하면
# (2,3,4) 행태의 첫번째 2가 가 날아가고 배열은 (3,4) 행태가된다. 즉 첫번째 차원 요소를 합해서 제거한다.
#[[1. 1. 1. 1.]           [[1. 1. 1. 1.]       [[2. 2. 2. 2.]
#  [1. 1. 1. 1.]     +     [1. 1. 1. 1.]    =    [2. 2. 2. 2.]
#  [1. 1. 1. 1.]]          [1. 1. 1. 1.]]        [2. 2. 2. 2.]]
sum0 = one.sum(axis=0)
print(sum0)
print(sum0.shape)


# 3차원 배열의 첫번째 축(Axis=1)를 기준으로 sum을 수행하면
# (2,3,4) 행태의 두번째 3가 가 날아가고 배열은 (2,4) 행태가된다. 즉 두번째 차원 요소를 합해서 제거한다.
# 1행) [1. 1. 1. 1.] + [1. 1. 1. 1.] + [1. 1. 1. 1.] = [3. 3. 3. 3.]                                                       
# 2행) [1. 1. 1. 1.] + [1. 1. 1. 1.] + [1. 1. 1. 1.] = [3. 3. 3. 3.]
#                                ▼
#                         [[3. 3. 3. 3.]
#                          [3. 3. 3. 3.]]

sum1 = one.sum(axis=1)
print(sum1)
print(sum1.shape)


# 3차원 배열의 첫번째 축(Axis=2)를 기준으로 sum을 수행하면
# (2,3,4) 행태의 세번째 4가 가 날아가고 배열은 (2,3) 행태가된다. 즉 세번째 차원 요소를 합해서 제거한다.
# 1행) [1 + 1 + 1 + 1], [1 + 1 + 1 + 1] , [1 + 1 + 1 + 1] = [4. 4. 4.]                                                       
# 2행) [1 + 1 + 1 + 1], [1 + 1 + 1 + 1] , [1 + 1 + 1 + 1] = [4. 4. 4.]
#                                ▼
#                         [[4. 4. 4.]
#                          [4. 4. 4.]]

sum2 = one.sum(axis=2)
print(sum2)
print(sum2.shape)


(2, 3, 4)
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
(3, 4)
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]
(2, 4)
[[4. 4. 4.]
 [4. 4. 4.]]
(2, 3)
