In [3]:
import tensorflow as tf
import numpy as np

In [2]:
action = 2
action_size = 4

# one_hot encoding 형태 만들기
one_hot_action = tf.one_hot([action], action_size)
print(one_hot_action) # 형태가 2차원 배열

tf.Tensor([[0. 0. 1. 0.]], shape=(1, 4), dtype=float32)


In [5]:
predict = np.random.randn((4))
print(predict)

[ 1.81051043  0.22369603 -0.16417762 -0.51549275]


In [8]:
# one_hot(1x4) 과 predict(4) 곱 결과는 (1,4)
one_hot_action*predict

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 1., 0.]], dtype=float32)>

In [6]:
# one_hot(1x4) 과 predict(4) 곱 결과가 (1,4) 임으로 축을 1 로 설정
pred = tf.reduce_sum(one_hot_action*predict, axis=1)
print(pred)

tf.Tensor([-0.16417761], shape=(1,), dtype=float32)
