## Numpy AXIS(축)의 이해

In [ ]:
# (2,3,4) 의 1로 구성된 3차원 배열
one = np.ones((2,3,4))
print(one)
print(one.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)


In [ ]:
# 3차원 배열의 첫번째 축(Axis=0)를 기준으로 sum을 수행하면
# (2,3,4) 행태의 첫번째 2가 가 날아가고 배열은 (3,4) 행태가된다. 즉 첫번째 차원 요소를 합해서 제거한다.
#[[1. 1. 1. 1.]           [[1. 1. 1. 1.]       [[2. 2. 2. 2.]
#  [1. 1. 1. 1.]     +     [1. 1. 1. 1.]    =    [2. 2. 2. 2.]
#  [1. 1. 1. 1.]]          [1. 1. 1. 1.]]        [2. 2. 2. 2.]]
sum0 = one.sum(axis=0)
print(sum0)
print(sum0.shape)


# 3차원 배열의 첫번째 축(Axis=1)를 기준으로 sum을 수행하면
# (2,3,4) 행태의 두번째 3가 가 날아가고 배열은 (2,4) 행태가된다. 즉 두번째 차원 요소를 합해서 제거한다.
# 1행) [1. 1. 1. 1.] + [1. 1. 1. 1.] + [1. 1. 1. 1.] = [3. 3. 3. 3.]                                                       
# 2행) [1. 1. 1. 1.] + [1. 1. 1. 1.] + [1. 1. 1. 1.] = [3. 3. 3. 3.]
#                                ▼
#                         [[3. 3. 3. 3.]
#                          [3. 3. 3. 3.]]

sum1 = one.sum(axis=1)
print(sum1)
print(sum1.shape)


# 3차원 배열의 첫번째 축(Axis=2)를 기준으로 sum을 수행하면
# (2,3,4) 행태의 세번째 4가 가 날아가고 배열은 (2,3) 행태가된다. 즉 세번째 차원 요소를 합해서 제거한다.
# 1행) [1 + 1 + 1 + 1], [1 + 1 + 1 + 1] , [1 + 1 + 1 + 1] = [4. 4. 4.]                                                       
# 2행) [1 + 1 + 1 + 1], [1 + 1 + 1 + 1] , [1 + 1 + 1 + 1] = [4. 4. 4.]
#                                ▼
#                         [[4. 4. 4.]
#                          [4. 4. 4.]]

sum2 = one.sum(axis=2)
print(sum2)
print(sum2.shape)


(2, 3, 4)
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
(3, 4)
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]
(2, 4)
[[4. 4. 4.]
 [4. 4. 4.]]
(2, 3)


## np.min()함수를 통해 이해하는 axis
<p>v 샘플데이터</p>
<img src="./images/np_min_data.png" width="20%">

<p>v axis=2 연산</p>
<p>2축 간의 데이터 중 최소값을 찾아 축내의 데이터를 1개로 만들어 1축을 제거</p>
<img src="./images/np_min_axis_2.png" width="50%">

<p>v axis=1 연산</p>
<p>1축 간의 데이터 중에서 최소값을 찾아 축내의 하위 차원을 1개로 만들어 1축을 제거</p>
<img src="./images/np_min_axis_1.png" width="50%">

<p>v axis=0 연산</p>
<p>0축에 포함된 3개의 하위차원 원소들을 각각 비교하여 최소값을 찾아 기존 3개 였던 0축의 하위차원을 하나로 만들어 0축을 제거</p>
<img src="./images/np_min_axis_0.png" width="50%">

<p>v axis=(0, 1) 연산</p>
<img src="./images/np_min_axis_01.png" width="100%">

<p>v axis=(1, 2) 연산</p>
<img src="./images/np_min_axis_12.png" width="100%">

<p>v axis=(2, 0) 연산</p>
<img src="./images/np_min_axis_20.png" width="100%">

In [ ]:
# axis=(a, b) 이해
arr = np.random.choice(100, (3,3,3))
print(arr)

min_axis2 = np.min(arr, axis=(2))
print("np.min(array, axis=(2)")
print(min_axis2)
min_axis1 = np.min(arr, axis=(1))
print("np.min(array, axis=(1)")
print(min_axis1)
min_axis0 = np.min(arr, axis=(0))
print("np.min(array, axis=(0)")
print(min_axis0)


min_axis1a2 = np.min(arr, axis=(1,2))
print("np.min(array, axis=(1,2)")
print(min_axis1a2)

min_axis2a1 = np.min(arr, axis=(2,1))
print("np.min(array, axis=(2,1)")
print(min_axis2a1)

min_axis0a1 = np.min(arr, axis=(0,1))
print("np.min(array, axis=(0,1)")
print(min_axis0a1)

min_axis1a0 = np.min(arr, axis=(1,0))
print("np.min(array, axis=(1,0)")
print(min_axis1a0)

min_axis0a2 = np.min(arr, axis=(0,2))
print("np.min(array, axis=(0,2)")
print(min_axis0a2)

min_axis2a0 = np.min(arr, axis=(2,0))
print("np.min(array, axis=(2,0)")
print(min_axis2a0)

[[[63 99 96]
  [86 25 63]
  [33 48 21]]

 [[69  1 34]
  [32 74 92]
  [64 21 61]]

 [[66 27 55]
  [72 26 58]
  [84 50  8]]]
np.min(array, axis=(2)
[[63 25 21]
 [ 1 32 21]
 [27 26  8]]
np.min(array, axis=(1)
[[33 25 21]
 [32  1 34]
 [66 26  8]]
np.min(array, axis=(0)
[[63  1 34]
 [32 25 58]
 [33 21  8]]
np.min(array, axis=(1,2)
[21  1  8]
np.min(array, axis=(2,1)
[21  1  8]
np.min(array, axis=(0,1)
[32  1  8]
np.min(array, axis=(1,0)
[32  1  8]
np.min(array, axis=(0,2)
[ 1 25  8]
np.min(array, axis=(2,0)
[ 1 25  8]
