In [2]:
import numpy as np

In [13]:
# 마스킹 수행
arr = np.random.randn(10, 5)  #  가우시안 표준 정규 분포에서 난수 matrix array생성
mask = np.random.choice(2, 10) # 0,1 로된 10개 원소로된 배열 생성
# arr = np.random.choice(2, (2,3)) => (2,3) 행렬 생성
#print(arr[mask>0])

x_train = np.random.choice(256, (60000, 784))
batch_size = 100
mask = np.random.choice(x_train.shape[0], batch_size)
x_batch = x_train[mask]
print(mask)
print(x_batch.shape)
print(x_batch)


[23609 29220 11586 37243 52773 39981 58476 41216 52174  8536  9651 26293
 48986 11546 25386 38973 52832  6406  9579 44687 38971 59901  2476  6577
 56599 46267 32898 12908 40703 40534 23453  6409 40401 15146 33732 46585
 25023 22364 15181 55402 56031 24007 40712   892 32712  9587 55900 41444
 56462 57003 26225 16435 26639  4980 50306 59222 27964 16132  3676 28039
 52070 20557 46527  1143 57590 33194 12477 36455 41751 39110 46646 55748
 57311 24017 40678  1854 24169 35672 30914 18341 45402 49349    58 14882
 58852 31185 50143 54496 59664 28936  1029 31474 46643 40486 53565 53344
 53552 25011 13730 36839]
(100, 784)
[[100  67 147 ... 249   4 159]
 [  5 162  81 ... 100 107 159]
 [169   1  82 ... 186 147 119]
 ...
 [ 33  29 158 ... 156  45 210]
 [136   1  18 ... 237 228  79]
 [ 16   7  20 ... 145 101  12]]


In [3]:
# 넘파이 색인 추출 방법
y = np.random.uniform(low=0, high=1, size=(5,3))
print(y)
t = np.array([0, 2, 1, 2, 1])
y[np.arange(y.shape[0]), t]
#np.log(0.09)


[[8.25647356e-01 9.86144540e-01 4.20728259e-04]
 [2.63463482e-01 7.78686958e-01 7.40818429e-01]
 [2.79943460e-01 5.61488499e-01 6.57844129e-01]
 [8.25124314e-01 8.54676385e-02 6.86121867e-01]
 [1.62839117e-01 7.30425223e-01 6.57519011e-01]]


array([0.82564736, 0.74081843, 0.5614885 , 0.68612187, 0.73042522])

In [3]:
# 랜덤으로(0~99)사이의 50개의 원소를 갖는 배열 생성
np.random.choice(100, 50)

array([40, 66, 84, 59,  3, 31, 35, 44, 51, 61, 89, 60, 50, 75, 97, 70, 14,
       58, 72, 67, 46,  3, 94, 44, 68, 82, 61, 68, 67, 47, 78, 47,  7, 11,
       92, 48, 14, 11, 53, 89, 11, 39, 74, 65, 14, 27, 37, 20,  5, 43])

In [16]:
np.sum(y, axis=0)

array([2.80719214, 2.41315958, 2.95459538])

In [9]:
arr = np.zeros((1,10))
arr[0, 0] = 1
print(arr)

arr = np.empty((0, 10), int)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[]


In [5]:
y = np.random.uniform(low=0, high=1, size=(2,3))
t = np.zeros((2,3))
t[0][0] = 1
t[1][1] = 1
print("y: ")
print(y)

delta = 1e-7 # log(0) 방지용
# np.log(x) (x>0)
e1 = t*np.log(y+delta) # cross entropy error
print("e1: ")
print(e1)
# sum( cross entropy error )
print("sum cross entropy error: ")
print(np.sum(e1, axis=1))

y: 
[[0.86767289 0.03754838 0.19354115]
 [0.16299771 0.58652077 0.84423812]]
e1: 
[[-0.14194038 -0.         -0.        ]
 [-0.         -0.53354703 -0.        ]]
sum cross entropy error: 
[-0.14194038 -0.53354703]


In [4]:
arr = np.random.choice(2, 10)
tf_arr = arr > 0 # 마스킹
print(tf_arr)

[False  True False  True False False  True False  True  True]


In [10]:
a = np.arange(4).reshape((2,2))
b = np.arange(4, 8, 1).reshape((2,2))

print(a)
print(b)

np.dot(a,b)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


array([[ 6,  7],
       [26, 31]])

In [3]:
# np.linspace(start, end, num)
# I makes 48 values from 0.1 to 4.8
np_sam = np.linspace(0.1, 4.8, num = 48)
np_sam

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9,
       4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8])

In [6]:
# np.insert() 행렬에 값 삽입하기
array = np.array([[[1, 1, 1, 1],
               [2, 2, 2, 2],
               [3, 3, 3, 3],],
              
              [[4, 4, 4, 4],
               [5, 5, 5, 5],
               [6, 6, 6, 6],]])

result = np.insert(array, 0, 10, axis=2)
print(result)

[[[10  1  1  1  1]
  [10  2  2  2  2]
  [10  3  3  3  3]]

 [[10  4  4  4  4]
  [10  5  5  5  5]
  [10  6  6  6  6]]]
