In [1]:
import numpy as np

In [13]:
# 마스킹 수행
arr = np.random.randn(10, 5)  #  가우시안 표준 정규 분포에서 난수 matrix array생성
mask = np.random.choice(2, 10) # 0,1 로된 10개 원소로된 배열 생성
# arr = np.random.choice(2, (2,3)) => (2,3) 행렬 생성
#print(arr[mask>0])

x_train = np.random.choice(256, (60000, 784))
batch_size = 100
mask = np.random.choice(x_train.shape[0], batch_size)
x_batch = x_train[mask]
print(mask)
print(x_batch.shape)
print(x_batch)


[23609 29220 11586 37243 52773 39981 58476 41216 52174  8536  9651 26293
 48986 11546 25386 38973 52832  6406  9579 44687 38971 59901  2476  6577
 56599 46267 32898 12908 40703 40534 23453  6409 40401 15146 33732 46585
 25023 22364 15181 55402 56031 24007 40712   892 32712  9587 55900 41444
 56462 57003 26225 16435 26639  4980 50306 59222 27964 16132  3676 28039
 52070 20557 46527  1143 57590 33194 12477 36455 41751 39110 46646 55748
 57311 24017 40678  1854 24169 35672 30914 18341 45402 49349    58 14882
 58852 31185 50143 54496 59664 28936  1029 31474 46643 40486 53565 53344
 53552 25011 13730 36839]
(100, 784)
[[100  67 147 ... 249   4 159]
 [  5 162  81 ... 100 107 159]
 [169   1  82 ... 186 147 119]
 ...
 [ 33  29 158 ... 156  45 210]
 [136   1  18 ... 237 228  79]
 [ 16   7  20 ... 145 101  12]]


In [10]:
# 넘파이 색인 추출 방법
y = np.random.uniform(low=0, high=1, size=(5,3))
print(y)
t = np.array([0, 2, 1, 2, 1])
y[np.arange(y.shape[0]), t]
np.log(0.09)


[[0.35933313 0.98033738 0.75179272]
 [0.61854777 0.69154466 0.94104401]
 [0.7751151  0.54588286 0.95413146]
 [0.54519846 0.98297737 0.59005639]
 [0.25156742 0.49114662 0.27117579]]


-2.4079456086518722

In [3]:
# 랜덤으로(0~99)사이의 50개의 원소를 갖는 배열 생성
np.random.choice(100, 50)

array([40, 66, 84, 59,  3, 31, 35, 44, 51, 61, 89, 60, 50, 75, 97, 70, 14,
       58, 72, 67, 46,  3, 94, 44, 68, 82, 61, 68, 67, 47, 78, 47,  7, 11,
       92, 48, 14, 11, 53, 89, 11, 39, 74, 65, 14, 27, 37, 20,  5, 43])

In [16]:
np.sum(y, axis=0)

array([2.80719214, 2.41315958, 2.95459538])

In [9]:
arr = np.zeros((1,10))
arr[0, 0] = 1
print(arr)

arr = np.empty((0, 10), int)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[]


In [17]:
y = np.random.uniform(low=0, high=1, size=(2,3))
t = np.zeros((2,3))
t[0][0] = 1
t[1][1] = 1

print(y)

delta = 1e-7
# np.log(x) (x>0)
e1 = t*np.log(y+delta)
print(e1)
print(np.sum(e1, axis=1))

[[0.41813702 0.11545386 0.34513503]
 [0.59952392 0.80031804 0.38517773]]
[[-0.87194587 -0.         -0.        ]
 [-0.         -0.22274595 -0.        ]]
[-0.87194587 -0.22274595]


In [4]:
arr = np.random.choice(2, 10)
tf_arr = arr > 0 # 마스킹
print(tf_arr)

[False  True False  True False False  True False  True  True]


In [10]:
a = np.arange(4).reshape((2,2))
b = np.arange(4, 8, 1).reshape((2,2))

print(a)
print(b)

np.dot(a,b)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


array([[ 6,  7],
       [26, 31]])

## Numpy AXIS(축)의 이해

In [30]:
# (2,3,4) 의 1로 구성된 3차원 배열
one = np.ones((2,3,4))
print(one)
print(one.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)


In [28]:
# 3차원 배열의 첫번째 축(Axis=0)를 기준으로 sum을 수행하면
# (2,3,4) 행태의 첫번째 2가 가 날아가고 배열은 (3,4) 행태가된다. 즉 첫번째 차원 요소를 합해서 제거한다.
#[[1. 1. 1. 1.]           [[1. 1. 1. 1.]       [[2. 2. 2. 2.]
#  [1. 1. 1. 1.]     +     [1. 1. 1. 1.]    =    [2. 2. 2. 2.]
#  [1. 1. 1. 1.]]          [1. 1. 1. 1.]]        [2. 2. 2. 2.]]
sum0 = one.sum(axis=0)
print(sum0)
print(sum0.shape)


# 3차원 배열의 첫번째 축(Axis=1)를 기준으로 sum을 수행하면
# (2,3,4) 행태의 두번째 3가 가 날아가고 배열은 (2,4) 행태가된다. 즉 두번째 차원 요소를 합해서 제거한다.
# 1행) [1. 1. 1. 1.] + [1. 1. 1. 1.] + [1. 1. 1. 1.] = [3. 3. 3. 3.]                                                       
# 2행) [1. 1. 1. 1.] + [1. 1. 1. 1.] + [1. 1. 1. 1.] = [3. 3. 3. 3.]
#                                ▼
#                         [[3. 3. 3. 3.]
#                          [3. 3. 3. 3.]]

sum1 = one.sum(axis=1)
print(sum1)
print(sum1.shape)


# 3차원 배열의 첫번째 축(Axis=2)를 기준으로 sum을 수행하면
# (2,3,4) 행태의 세번째 4가 가 날아가고 배열은 (2,3) 행태가된다. 즉 세번째 차원 요소를 합해서 제거한다.
# 1행) [1 + 1 + 1 + 1], [1 + 1 + 1 + 1] , [1 + 1 + 1 + 1] = [4. 4. 4.]                                                       
# 2행) [1 + 1 + 1 + 1], [1 + 1 + 1 + 1] , [1 + 1 + 1 + 1] = [4. 4. 4.]
#                                ▼
#                         [[4. 4. 4.]
#                          [4. 4. 4.]]

sum2 = one.sum(axis=2)
print(sum2)
print(sum2.shape)


(2, 3, 4)
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
(3, 4)
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]
(2, 4)
[[4. 4. 4.]
 [4. 4. 4.]]
(2, 3)


## np.min()함수를 통해 이해하는 axis
<p>v 샘플데이터</p>
<img src="./images/np_min_data.png" width="20%">

<p>v axis=2 연산</p>
<p>2축 간의 데이터 중 최소값을 찾아 축내의 데이터를 1개로 만들어 1축을 제거</p>
<img src="./images/np_min_axis_2.png" width="50%">

<p>v axis=1 연산</p>
<p>1축 간의 데이터 중에서 최소값을 찾아 축내의 하위 차원을 1개로 만들어 1축을 제거</p>
<img src="./images/np_min_axis_1.png" width="50%">

<p>v axis=0 연산</p>
<p>0축에 포함된 3개의 하위차원 원소들을 각각 비교하여 최소값을 찾아 기존 3개 였던 0축의 하위차원을 하나로 만들어 0축을 제거</p>
<img src="./images/np_min_axis_0.png" width="50%">

<p>v axis=(0, 1) 연산</p>
<img src="./images/np_min_axis_01.png" width="100%">

<p>v axis=(1, 2) 연산</p>
<img src="./images/np_min_axis_12.png" width="100%">

<p>v axis=(2, 0) 연산</p>
<img src="./images/np_min_axis_20.png" width="100%">

In [20]:
# axis=(a, b) 이해
arr = np.random.choice(100, (3,3,3))
print(arr)

min_axis2 = np.min(arr, axis=(2))
print("np.min(array, axis=(2)")
print(min_axis2)
min_axis1 = np.min(arr, axis=(1))
print("np.min(array, axis=(1)")
print(min_axis1)
min_axis0 = np.min(arr, axis=(0))
print("np.min(array, axis=(0)")
print(min_axis0)


min_axis1a2 = np.min(arr, axis=(1,2))
print("np.min(array, axis=(1,2)")
print(min_axis1a2)

min_axis2a1 = np.min(arr, axis=(2,1))
print("np.min(array, axis=(2,1)")
print(min_axis2a1)

min_axis0a1 = np.min(arr, axis=(0,1))
print("np.min(array, axis=(0,1)")
print(min_axis0a1)

min_axis1a0 = np.min(arr, axis=(1,0))
print("np.min(array, axis=(1,0)")
print(min_axis1a0)

min_axis0a2 = np.min(arr, axis=(0,2))
print("np.min(array, axis=(0,2)")
print(min_axis0a2)

min_axis2a0 = np.min(arr, axis=(2,0))
print("np.min(array, axis=(2,0)")
print(min_axis2a0)

[[[63 99 96]
  [86 25 63]
  [33 48 21]]

 [[69  1 34]
  [32 74 92]
  [64 21 61]]

 [[66 27 55]
  [72 26 58]
  [84 50  8]]]
np.min(array, axis=(2)
[[63 25 21]
 [ 1 32 21]
 [27 26  8]]
np.min(array, axis=(1)
[[33 25 21]
 [32  1 34]
 [66 26  8]]
np.min(array, axis=(0)
[[63  1 34]
 [32 25 58]
 [33 21  8]]
np.min(array, axis=(1,2)
[21  1  8]
np.min(array, axis=(2,1)
[21  1  8]
np.min(array, axis=(0,1)
[32  1  8]
np.min(array, axis=(1,0)
[32  1  8]
np.min(array, axis=(0,2)
[ 1 25  8]
np.min(array, axis=(2,0)
[ 1 25  8]
